language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - DJANGO_VERSION=1.5 TEST_LOCATION=easy_thumbnails
  - DJANGO_VERSION=1.6 TEST_LOCATION=easy_thumbnails
  - DJANGO_VERSION=1.7 TEST_LOCATION=easy_thumbnails.tests

install:
  - pip install --use-mirrors "Django<$DJANGO_VERSION"
  - pip install --use-mirrors testfixtures
  - pip install --use-mirrors .

script:
  - django-admin.py test $TEST_LOCATION --settings=easy_thumbnails.test_settings --traceback

matrix:
  exclude:
    - env: DJANGO_VERSION=1.5 TEST_LOCATION=easy_thumbnails
      python: "3.3"
