language: python

python:
  - "2.6"
  - "2.7"

env:
  - PYTHONPATH=$PYTHONPATH:$PWD DJANGO_VERSION=1.5
  - PYTHONPATH=$PYTHONPATH:$PWD DJANGO_VERSION=1.6

install:
  - pip install --use-mirrors Django<$DJANGO_VERSION

script:
  - django-admin.py test easy_thumbnails --settings=easy_thumbnails.test_settings
